### ISSUE TITLE
Property cards are showing wrong bed, bath, sqft values.

### ISSUE THREAD

**Issue by anubhavsinha** [opscaled/reddoor#1]
We are getting a 3 for everything. 

<img width="1280" alt="screen shot 2017-09-13 at 5 19 19 am" src="https://user-images.githubusercontent.com/1009901/30353384-2ec534fe-9843-11e7-9c97-8399b2794cc7.png">

**Comment by Sidhi-dhall** [comment]
I have set the property cards to show correct values
