### ISSUE TITLE
Site by VCS is missing the link.

### ISSUE THREAD

**Issue by anubhavsinha** [opscaled/reddoor#3]
Please check the fix for all the pages.
Link it to https://www.vcsinc.com/bay-area-technology-solutions
and text should be Value-Centered Solutions, Inc. (s is missing)

**Comment by Sidhi-dhall** [comment]
I have added the VCS link in the footer of the site.

**Comment by lelab144** [comment]
text should be Value-Centered Solutions, Inc. (s is missing)
