### ISSUE TITLE
Background Image for Featured Listings section of home page

### ISSUE THREAD

**Issue by lelab144** [opscaled/reddoor#5]
where is this so we can change as needed?

**Comment by Sidhi-dhall** [comment]
Please login to the admin account using the following details:
http://www.reddoortyler.com/wp-admin/
username: ########
password: ########

After that, go to Pages -> then click on Homepage ( http://www.reddoortyler.com/wp-admin/post.php?post=194&action=edit) 
Then check the screenshot step1.png
![step1](https://user-images.githubusercontent.com/28038485/30364228-f4cb4ade-9880-11e7-8943-f1875e2f2480.png)

after that go the "Design Options" and check the screenshot step2.png
![step2](https://user-images.githubusercontent.com/28038485/30364286-2df5f4c6-9881-11e7-98d5-3fe0da350da0.png)
You can change the image and

after that click "Save Changes" and after that Click on "Update" button in the right side of the page.
